// <auto-generated />
namespace Dex_API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Icollection_To_IList : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Icollection_To_IList));
        
        string IMigrationMetadata.Id
        {
            get { return "201801182047420_Icollection_To_IList"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
