// <auto-generated />
namespace DEX.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Address_AddedTo_Companies : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Address_AddedTo_Companies));
        
        string IMigrationMetadata.Id
        {
            get { return "201606141656175_Address_AddedTo_Companies"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
