// <auto-generated />
namespace DEX.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Company_ApplicationUser_Renamed_User : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Company_ApplicationUser_Renamed_User));
        
        string IMigrationMetadata.Id
        {
            get { return "201701192311073_Company_ApplicationUser_Renamed_User"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
