// <auto-generated />
namespace DEX.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CascadingDeletes_Addedto_OnModelCreating : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CascadingDeletes_Addedto_OnModelCreating));
        
        string IMigrationMetadata.Id
        {
            get { return "201701170219246_CascadingDeletes_Addedto_OnModelCreating"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
